/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package guessinggame;

import java.util.Random;
import java.util.Scanner;

// Main class
public class NumberGuessingGame {
    public static void main(String[] args) {
        Game game = new Game(1, 100); // Range from 1 to 100
        game.start();
    }
}

// Game class
class Game {
    private int lowerBound;
    private int upperBound;
    private int targetNumber;
    private Scanner scanner;
    private int attempts;

    // Constructor
    public Game(int lowerBound, int upperBound) {
        this.lowerBound = lowerBound;
        this.upperBound = upperBound;
        this.targetNumber = generateTargetNumber();
        this.scanner = new Scanner(System.in);
        this.attempts = 0;
    }

    // Generate a random target number within the given range
    private int generateTargetNumber() {
        Random random = new Random();
        return random.nextInt(upperBound - lowerBound + 1) + lowerBound;
    }

    // Start the game
    public void start() {
        System.out.println("Welcome to the Number Guessing Game!");
        System.out.println("I have selected a number between " + lowerBound + " and " + upperBound + ".");
        System.out.println("Can you guess it?");

        boolean hasGuessedCorrectly = false;

        while (!hasGuessedCorrectly) {
            System.out.print("Enter your guess: ");
            int guess = getValidInput();
            attempts++;
            hasGuessedCorrectly = checkGuess(guess);
        }

        System.out.println("Congratulations! You've guessed the correct number in " + attempts + " attempts.");
        scanner.close();
    }

    // Get valid input from the user
    private int getValidInput() {
        while (true) {
            String input = scanner.nextLine();
            try {
                int guess = Integer.parseInt(input);
                if (guess < lowerBound || guess > upperBound) {
                    throw new NumberFormatException();
                }
                return guess;
            } catch (NumberFormatException e) {
                System.out.print("Invalid input. Please enter a number between " + lowerBound + " and " + upperBound + ": ");
            }
        }
    }

    // Check the user's guess against the target number
    private boolean checkGuess(int guess) {
        if (guess < targetNumber) {
            System.out.println("Too low! Try again.");
            return false;
        } else if (guess > targetNumber) {
            System.out.println("Too high! Try again.");
            return false;
        } else {
            return true;
        }
    }
}

// Utility class for handling the range of numbers
class Range {
    private int lower;
    private int upper;

    public Range(int lower, int upper) {
        this.lower = lower;
        this.upper = upper;
    }

    public int getLower() {
        return lower;
    }

    public int getUpper() {
        return upper;
    }

    public boolean isInRange(int number) {
        return number >= lower && number <= upper;
    }
}

// Class to handle user input validation
class InputValidator {
    public static int validateInput(String input, Range range) throws NumberFormatException {
        int number = Integer.parseInt(input);
        if (!range.isInRange(number)) {
            throw new NumberFormatException();
        }
        return number;
    }
}